### ISSUE TITLE
SLM double quote conversion in section 13

### ISSUE THREAD

**Issue by dmaggert-igs** [International-GNSS-Service/SLM#35]
<img width="761" alt="OBE4" src="https://github.com/International-GNSS-Service/SLM/assets/113188446/de191686-d2da-46ed-9603-8a9dbf393a7c">

Double quote is converted into &#34 in section 13 antenna drawing section

**Comment by dmaggert-igs** [comment]
I noticed this conversion problem in section 0 of the Prepared by field for TEJA00CHL so this probably effects other fields as well and not just section 13.

**Comment by bckohan** [comment]
This appears to be an issue with the data itself. There's nothing in the software thats escaping the string. This probably happened during import.

It does raise a question though. Is the correct solution just to fix our data or is the correct solution to forcibly unescape all text strings during serialization.
